# Disable sudo to speed up the build
sudo: false

dist: trusty

language: python

python:
  - "3.6"

script:
  - sonar-scanner

addons:
  sonarcloud:
    organization: "lieturd"
    token: $SONAR_TOKEN
